# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: madcamp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: me


provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2  # 서울 리전

functions:
  getAllQuestions:
    handler: handlers/getAllQuestions.getAllQuestions
    events:
      - httpApi:
          path: /questions
          method: get

plugins:
  - serverless-offline
